name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # setiap kali push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # penting biar bisa push ke gh-pages

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
